# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: 2.1.300

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    projects: src/jupyter-core.csproj'
    versioningScheme: byPrereleaseNumber

- task: DotNetCoreCLI@2
  inputs:
    command: push
    publishVstsFeed: https://quarcsw.pkgs.visualstudio.com/_packaging/alpha/nuget/v3/index.json
    allowPackageConflicts: true
